### ISSUE TITLE
connect to specific device?

### ISSUE THREAD

**Issue by farhanito** [eschava/broadlink-mqtt#1]
hi,

instead of using device discovery
`devices = broadlink.discover(timeout=lookup_timeout)`

can we use setdevice function like
`device = broadlink.rm(host=("192.168.1.10",80), mac=bytearray.fromhex("b4 43 0d d1 00 00"))
`

thanks

**Comment by eschava** [comment]
Fixed. Do you have several broadlink devices in network?

**Comment by farhanito** [comment]
Thanks for this.

Yes, i have several broadlink devices, one of them is a wifi socket (SPcc).

Anyway,  what's the best way to use more than one broadlink RM devices? By running multiple instances of your codes?

Thanks again

**Comment by eschava** [comment]
Yes, now it's possible only running multiple instances of the app
I have in plans implementing something like "multiple devices" mode and in this case MQTT topic should have some information to select correct broadlink instance, like **broadlink/macD10000/samsung/power**, where D1:00:00 are last 3 numbers from device MAC address

**Comment by farhanito** [comment]
excellent, thanks

btw, i got this error:
`Traceback (most recent call last):
  File "./mqtt.py", line 144, in <module>
    logging.debug('Connected to %s Broadlink device at %s' % (device.type, device.host))
AttributeError: rm instance has no attribute 'type'
`

**Comment by eschava** [comment]
Looks very strange
could you please try to replace line #144
    logging.debug('Connected to %s Broadlink device at %s' % (device.type, device.host))
with
    logging.debug('Connected to %s Broadlink device at %s' % (device.get_type(), device.host))
?

**Comment by farhanito** [comment]
`Traceback (most recent call last):
  File "./mqtt.py", line 144, in <module>
    logging.debug('Connected to %s Broadlink device at %s' % (device.get_type(), device.host))
AttributeError: rm instance has no attribute 'get_type'
`

quoting that line and everything works fine

**Comment by eschava** [comment]
could you please check what's current version of broadlink python library installed at your box?

**Comment by farhanito** [comment]
ah, that's it..
updated the module

thanks

**Comment by eschava** [comment]
Hi. If you're still interested - I've committed support for using several Broadlink devices
See docs at https://github.com/eschava/broadlink-mqtt#multiple-devices-configuration
