### ISSUE TITLE
More Codes if you want them

### ISSUE THREAD

**Issue by psyciknz** [eschava/broadlink-mqtt#11]
I have a harmony remote, their database includes individual buttons for hdmi1 - 4 etc.  I've got those as code for the rm3 if you want.

**Comment by eschava** [comment]
Sorry, not clear for me
You have some IR codes in format used by this tool?

**Comment by psyciknz** [comment]
Yes.  Recorded with your tool, codes for hdmi, hdmi2, 3 and 4. Plus tv button.  Your codes from GitHub worked for me, so these may work for you.

**Comment by eschava** [comment]
As far as I understand Harmony remote is universal remote working with many devices. What device your codes were recorded for?

**Comment by psyciknz** [comment]
A samsung 2008 TV.  It uses the B59 Remote.  The power, volume commands you have here in github worked for me...so maybe these might work for you.

**Comment by eschava** [comment]
Could you please create a pull request?

**Comment by eschava** [comment]
Merged. Thank you!
