### ISSUE TITLE
Bind to ip of interface?

### ISSUE THREAD

**Issue by heikoh81** [eschava/broadlink-mqtt#116]
Hello,

I have assigned several static ips to eth0 on my raspberry.
Is there an option to bind broadlink-mqtt to listen only on 1 of these adresses?

I found this in the sample mqtt.conf:
_lookup parameters
lookup_timeout = 20
local_address = '127.0.0.1'`_
But local_adress is in the lookup parameters sections - which does not make sense to me?
Will broadlink-mqtt listen to only the ip specified after local_adress = ?

Thanks for any advice,
Heiko

**Comment by eschava** [comment]
Hi
Actually broadlink-mqtt doesn't create any server sockets, it creates only client sockets for connection to broadlink devices + connection to the MQTT broker

**Comment by heikoh81** [comment]
Thanks for your reply.
I understand.

Is it possible to tell broadlink-mqtt to use a specific client ip to connect to the mqtt broker, if I have assigned multiple ips to eth0?

**Comment by eschava** [comment]
I've added mqtt_bind configuration parameter. Please check it

**Comment by heikoh81** [comment]
Thank you very much for the fast implementation.
I can confirm that it works and binds correctly.
