### ISSUE TITLE
Multiple RM3 devices

### ISSUE THREAD

**Issue by psyciknz** [eschava/broadlink-mqtt#13]
How will this work?  I've just bought a 2nd.  But I corrently specify in the mqtt.cong the ip and mac address.

Is it possible to get 2 running?

**Comment by eschava** [comment]
Actually this feature is not supported yet
But you can run two instances of the tool with different config files (installed in two different folders or run with specified BROADLINKMQTTCONFIG env variable)
Both configurations in this case should have correct device_type/device_type/device_mac parameters specified, 'lookup' will not work correctly

**Comment by psyciknz** [comment]
Yeah I had a look through the code today.  When I get my 2nd I might see if I can implement it.

**Comment by eschava** [comment]
Hi. If you're still interested - I've committed support for using several Broadlink devices
See docs at https://github.com/eschava/broadlink-mqtt#multiple-devices-configuration

**Comment by psyciknz** [comment]
Had a quick look, looks cleaner than what I did, I think I assumed every multiple device was a RM2 where you tacked on the device type to the definition.
