### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by Blue407** [eschava/broadlink-mqtt#15]
This looks very promising, I have a unit on order :)

Can I control other Broadlink devices with your scripts? such as light switches etc?

**Comment by Blue407** [comment]
Great news :)

I have one of these on order.  [https://www.banggood.com/Broadlink-RM-Pro-Wifi-Universal-Remote-Controller-Match-with-Digoo-RC-13-RF-Remote-Control-Socket-p-1075617.html?rmmds=category](url)

How about the recommended light dimmer switches?

[https://hartingtonheath.com/product/i-lumos-luxury-white-crystal-glass-touch-wifi-remote-dimmer-led-light-switches/](url)

**Comment by eschava** [comment]
Sorry, no idea about light dimmers
