### ISSUE TITLE
Mapping a MQTT command to a Rollershutter Button

### ISSUE THREAD

**Issue by gajpchapo** [eschava/broadlink-mqtt#16]
I have set up an item for Samsung TV Volume using the Rollershutter item type.  The issue with this is that the commands only refer to channelup and channeldown.  Therefore, when you assign channelup to a Rollershutter item type it will change the TV channel up whether you press the up button or the down button.  In order to work around this I did the following;

Rollershutter Broadlink_Samsung_channel <network> {mqtt=">[broker:broadlink/tv/samsung/channelup:command:*:auto],>[broker:broadlink/tv/samsung/channeldown:command:*:auto]"}

However, when I press either button now it firstly sends the TV up a channel and then immediately down a channel so you end up where you started.

Can anybody help here please?

**Comment by eschava** [comment]
I do not have enough experience with configuring roller shutters but after checking forum I can suggest next configuration:

Rollershutter RL_SZ "Schlafzimmer Fenster" (gOG,gShutterOG) {mqtt=">[broker:broadlink/tv/samsung/channelup:command:UP:auto],>[broker:broadlink/tv/samsung/channeldown:command:DOWN:auto]"}

**Comment by gajpchapo** [comment]
Works great!  Thanks for your help!
