### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by gajpchapo** [eschava/broadlink-mqtt#17]
Hi Eugene,

I have been trying to record a macro to allow me to have a two numbered television channel selected.  However, to date I have been unsuccessful.

item file setting

Switch Broadlink_Samsung_10 <switch> {mqtt=">[broker:broadlink/channel_10:macros:*:auto]"}

Are you able to assist me?

Thanks

**Comment by eschava** [comment]
Please use "macro" not "macros" message
