### ISSUE TITLE
Homebridge/HomeKit?

### ISSUE THREAD

**Issue by jat80** [eschava/broadlink-mqtt#20]
Can this work with Apple HomeKit or maybe something like homebridge?  I've used another homebridge plugin for the RM Mini 3 but find MQTT is so much more reliable. Thanks.

**Comment by eschava** [comment]
I think it could be used with HomeKit/Homebridge only if they support MQTT connectivity
E.g. you can use next flow broadlink-mqtt -> MQTT broker -> Homebridge MQTT plugin, if possible
