### ISSUE TITLE
Run on startup

### ISSUE THREAD

**Issue by QuagmireMan** [eschava/broadlink-mqtt#29]
I am trying to have the mqtt.py run on startup.  I added
`python /home/openhabian/broadlink-mqtt/mqtt.py &`
to rc.local, but it did not seem to trigger the script.

I also get errors when trying to execute mqtt.py from node red.  
`Traceback (most recent call last):  File "mqtt.py", line 3, in <module>    import paho.mqtt.client as paho  # pip install paho-mqttImportError: No module named paho.mqtt.client`

I assume that has to do with the way paho was installed and it can't find the module... but I haven't figured that out either.  I am assuming they might be related.

Is it something simple I am missing?

**Comment by eschava** [comment]
Maybe startup script runs mqtt.py under the root user while paho-mqtt library is installed for regular user?
Please try to execute
`sude pip install paho-mqtt`

**Comment by QuagmireMan** [comment]
Installed it with sudo, and I am still having the same issue.

**Comment by QuagmireMan** [comment]
Well, it looks like i needed to install broadlink with sudo and it fixed the problem.
`sudo pip install paho-mqtt broadlink`

Thank you for the help!

**Comment by pabloreadi** [comment]
hello, I'm windows user and I run on startup mqtt.py and it's ok.
I need to know if mqtt.py can run like a service?

**Comment by eschava** [comment]
Sorry, I have no experience with Windows services.
Somebody on the StackOverflow suggested using http://nssm.cc/ for managing user services
Could you please try it and tell if it helps

**Comment by pabloreadi** [comment]
I tried it and it's works fine!!
I use Windows 10, then I downloaded the last version, 

- I must run **cmd** like an administrator
- nssm install **servicename**
- then in edit windows:
path: C:\Python27\python.exe
Startup directory: C:\**directory of service**
Arguments: **servicename**

**Comment by VincentSC** [comment]
For documentation

> sudo pip install paho-mqtt broadlink

>  sudo nano /lib/systemd/system/broadlink-mqtt.service
```
[Unit]
Description=Broadlink MQTT Service
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 /home/pi/broadlink-mqtt/mqtt.py
StandardInput=tty-force

[Install]
WantedBy=multi-user.target
```
