### ISSUE TITLE
will it possible add check temperature and publish MQTT every few minutes?

### ISSUE THREAD

**Issue by hamwong** [eschava/broadlink-mqtt#3]
as RM actually have check temperature feature by check_temperature()
do you mind add this function and auto publish MQTT every x minutes and x value can set in mqtt.conf?

**Comment by eschava** [comment]
I've added configuration parameter broadlink_rm_temperature_interval but have no chance to check it
Please do if it is possible for you

**Comment by hamwong** [comment]
Thanks, I am in office now, will do it once back home,
Thanks again for your super fast add up and your hard work.

**Comment by hamwong** [comment]
I think I got some issue, first I change broadlink library to "https://github.com/johado/python-broadlink/tree/master/broadlink" version,
I can still work with you code with lookup
[2017-02-21 00:55:10,528] DEBUG Connected to RM2 Broadlink device at ('192.168.xxx.xxx', 80)
[2017-02-21 00:55:10,533] DEBUG Connected to MQTT broker, subscribing to topic broadlink/#

but with new version, I got
Traceback (most recent call last):
  File "mqtt.py", line 151, in <module>
    device = get_device(cf)
  File "mqtt.py", line 124, in get_device
    logging.error('More than one Broadlink device found (' + ', '.join([d.host for d in devices]) + ')')
TypeError: sequence item 0: expected string, tuple found

if I off power the power bar (broadlink MP1), it works,
but I don't see temperature pop up.

**Comment by eschava** [comment]
could you please share your config file?

**Comment by hamwong** [comment]
# Type of device. Valid options are 'lookup', 'rm', 'sp1', 'sp2', 'a1'
device_type = 'lookup' # use lookup

## lookup parameters
lookup_timeout = 20
#local_address = '192.168.xxx.xxx'

## parameters for direct connection
device_host = '192.168.xxx.xxx'
device_mac  = 'B4:43:0D:38:77:1D'

## MQTT connection parameters
mqtt_broker = 'localhost'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'broadlink'
mqtt_username = ''
mqtt_password = ''
mqtt_topic_prefix = 'broadlink/'

## extra parameters
broadlink_rm_temperature_interval = 120 # publish temperature from RM device to broadlink/temperature topic every two minutes

**Comment by hamwong** [comment]
by the way, during the time, I able to send command to RM for IR feature

**Comment by eschava** [comment]
I see that your device type is 'lookup'. In this case device_host/device_mac parameters are ignored
please check it to 'rm'

How do you check if temperature is sent every 2 minutes?

**Comment by hamwong** [comment]
I can't run on RM in config as I use a modified version of broadlink library,
I get error code as below


Traceback (most recent call last):
  File "mqtt.py", line 151, in <module>
    device = get_device(cf)
  File "mqtt.py", line 131, in get_device
    return broadlink.rm(host=host, mac=mac)
TypeError: __init__() takes exactly 4 arguments (3 given)

**Comment by eschava** [comment]
Right, there was a bug
please check now

**Comment by hamwong** [comment]
I got it right on first run, than try to run on in conf with rm, still same error from modified library,
than I try with lookup again, than it's wired, I keep have below log until I unplug MP1

  File "mqtt.py", line 175, in <module>
    device = get_device(cf)
  File "mqtt.py", line 128, in get_device
    logging.error('More than one Broadlink device found (' + ', '.join([d.host for d in devices]) + ')')

and yes, this time I got temp from MQTT 
[2017-02-21 01:59:10,652] DEBUG Sending RM temperature 23.4 to topic broadlink/temperature

XD
Thanks
