### ISSUE TITLE
Record

### ISSUE THREAD

**Issue by pabloreadi** [eschava/broadlink-mqtt#31]
Hello, I could connect to my rm broadlink and mqtt broker!!
`[2018-06-29 12:23:57,227] DEBUG Connected to RM2 Broadlink device at '192.168.1.108' (MAC 78:0f:77:00:b6:34)
[2018-06-29 12:23:58,289] DEBUG Connected to MQTT broker, subscribing to topic broadlink/#`

Then, where must I send a record message like this? record -> broadlink/tv/samsung/power 
in python shell?
I'm a beginner in python...

**Comment by eschava** [comment]
This utility works with MQTT protocol and when you see in the docs something like "record -> broadlink/tv/samsung/power" it means that you have to send message "record" to the MQTT broker on the topic "broadlink/tv/samsung/power"

**Comment by pabloreadi** [comment]
OK, but from where I have to send the message?. From MQTT broker? from mqtt.py?

**Comment by eschava** [comment]
This utility created for automatization projects (like smart homes)
For single sending, it's better to use something like https://github.com/mjg59/python-broadlink/tree/master/cli

**Comment by pabloreadi** [comment]
OK, thanks.
