### ISSUE TITLE
Energy value

### ISSUE THREAD

**Issue by pabloreadi** [eschava/broadlink-mqtt#32]
Hello, I'm using multiple_lookup with RM2 and SP2. I operate fine with both.
I have problem with the value of energy of SP2, because always inform "None" even when SP2 is on and connected with a tv on for example.

**Comment by eschava** [comment]
Sorry,
what kind of SP2 device do you have? Could you please send a link to the shop or photo?
Are you sure it has energy consumption feature?

**Comment by pabloreadi** [comment]
good question, I think all of SP2 have this functionality. This is the link: http://www.dx.com/p/broadlink-sp-mini3-smart-socket-wi-fi-timer-for-ios-or-android-white-457762#.W1Cf69UzaUk

**Comment by eschava** [comment]
No, this model (SP mini3) doesn't have it
You need SP2 or SP3S

**Comment by pabloreadi** [comment]
ok thanks
