### ISSUE TITLE
Help !! Trying to use this script in Home Assistant

### ISSUE THREAD

**Issue by emmc** [eschava/broadlink-mqtt#33]
How can i record a command  with a mqtt topic "broadlink/office/light1/" and payload on or off.
When i do this it does't work.

it works only with the topic "broadlink/office/light1/" without the payload.

I want to integrate with the home assistant and i need the payload_on: "ON" and payload_off: "OFF"

sorry my english!!!

great job

**Comment by eschava** [comment]
Sorry, but currently script understands only record/reply/auto payloads
I'm thinking about a new feature that will allow replaying commands using any payload.

E.g. to replay command from file "office/light1/on" you can send payload "on" to the "broadlink/office/light1" topic. But to record this command you still need to send payload "record" to the "broadlink/office/light/on" topic

Will it work?

**Comment by eschava** [comment]
Done
