### ISSUE TITLE
Broadlink SC1

### ISSUE THREAD

**Issue by razion12** [eschava/broadlink-mqtt#34]
hello I think the idea is great! it would be possible to extend the project and although this module (Broadlink SC1) to integrate
Request for feedback
Thanks in advance

**Comment by smartnakh** [comment]
You can use node-red for Sc1

**Comment by eschava** [comment]
Parent library (python-broadlink) still misses support for SC1 device
You can track changes for issue https://github.com/mjg59/python-broadlink/issues/142
But there is a comment that it should work the same way as sp2

Could you please manually specify the type of device and host/mac in configuration, like
```
device_type = 'sp2'
...
device_host = '192.168.1.50'
device_mac  = '01:23:45:67:ab:00'

```
to check if it really works?

**Comment by razion12** [comment]
thx

**Comment by razion12** [comment]
@eschava thx
