### ISSUE TITLE
auto run on pi3

### ISSUE THREAD

**Issue by cobra85ec** [eschava/broadlink-mqtt#37]
tryin to auto run on pi3 keep getting error ... can u help..?

**Comment by eschava** [comment]
What error are you getting?

**Comment by cobra85ec** [comment]
this is what i did
-sudo nano /etc/profile
then added to the bottom.
-python broadlink-mqtt/mqtt.py
save it then
-sudo reboot
when i log back in with putty this is what i get..

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Oct 26 06:46:52 2018 from 192.168.50.1
[2018-10-26 06:52:06,053] DEBUG Connected to RM2 Broadlink device at '192.168.50.179' (MAC e8:d4:50:77:0f:78)
Traceback (most recent call last):
  File "broadlink-mqtt/mqtt.py", line 389, in <module>
    mqttc.connect(cf.get('mqtt_broker', 'localhost'), int(cf.get('mqtt_port', '1883')), 60)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by eschava** [comment]
Looks like your mqtt server is run AFTER broadlink-mqtt
Could you please confirm?

**Comment by cobra85ec** [comment]
i dont kno how to do that.... but is there a way to add a delay to the start up..?

**Comment by eschava** [comment]
Sorry, I'm not an expert in the Linux
But you can try adding your line to /etc/rc.local, not /etc/profile

**Comment by cobra85ec** [comment]
i try that also same erro and i also try bashrc

**Comment by plains203** [comment]
I added mine to /etc/rc.local The command I used is as follows. Your path will vary.
nohup python /home/plains203/broadlink-mqtt/mqtt.py --mqtt >/dev/null 2>&1 &
sleep 1

**Comment by cobra85ec** [comment]
ok i got it. this let it wait 1min b4 it start  after my node red which runs my mqtt server.. thank u guys very much.
sleep 60 && python home/pi/broadlink-mqtt/mqtt.py
