### ISSUE TITLE
socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by revero11** [eschava/broadlink-mqtt#38]
Hi
i followed your tutorial for installation of brodlink-mqtt but i run mqtt.py with interpreter pyton i had this error from server:

Traceback (most recent call last):
  File "./mqtt.py", line 389, in <module>
    mqttc.connect(cf.get('mqtt_broker', 'localhost'), int(cf.get('mqtt_port', '1883')), 60)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
The installation of linux suite is on Rabsperry pi 0 and then there is Homeassistant also istalled. I try to open the port 1883 on the gateway but it's not resolve the problem 

this is my mqtt.config

 Type of device. Valid options are 'lookup', 'multiple_lookup', 'rm', 'sp1', 'sp2', 'a1', 'mp1'
device_type = 'multiple_lookup' # use lookup

## lookup parameters
lookup_timeout = 20
#local_address = '127.0.0.1'

## parameters for direct connection
#device_host = '192.168.1.64'
#device_mac  = 'b8:27:eb:d7:1b:10'
#device_mac  = '01:23:45:67:ab:00'

## MQTT connection parameters
mqtt_broker = 'localhost'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'broadlink'
mqtt_username = ''
mqtt_password = ''
mqtt_topic_prefix = 'broadlink/'
mqtt_multiple_subprefix_format = 'broadlink/MP1_db_9a_b9/'
mqtt_multiple_subprefix_format = 'broadlink/A _f9_0b_79/'
#mqtt_multiple_subprefix_format = '{type}_{mac_nic}/' 
# use only with 'multiple_lookup' device type (allowed parameters are {type}, {host}, {mac}, {mac_nic})

## MQTT TLS parameters
# Required with TLS: a string path to the Certificate Authority certificate files that are to be treated as trusted by this client.
# ca_certs = '/path/to/ca_certsfile'
# Optional Clients Cert/Key
# certfile = '/path/to/certfile'
# keyfile  = '/path/to/keyfile'
# Required TLS version. Valid values: 'sslv3', 'tlsv1', 'tlsv1.2'
# tls_version = 'tlsv1.2'

## extra parameters
broadlink_rm_temperature_interval = 120 # publish temperature from RM device to broadlink/temperature topic every two minutes
broadlink_sp_energy_interval = 30 # publish energy from SP device to broadlink/energy topic every 30 seconds
broadlink_a1_sensors_interval = 30 # publish all sensors data from A1 device to broadlink/sensors/[temperature/humidity/light/air_quality/noise] topics every 30 seconds
broadlink_a1_sensors_text_values = False # use True to send text representation of light/air quality/noise values
broadlink_a1_sensors_json = False # False to send every sensor parameter in separate topic, True - to send all together as JSON object
Do you have help me?
thanks so much
Revero11

**Comment by eschava** [comment]
Please check https://github.com/eschava/broadlink-mqtt/issues/27
