### ISSUE TITLE
No temperature data from RM Pro+

### ISSUE THREAD

**Issue by Sc0th** [eschava/broadlink-mqtt#40]
Hi, Thanks for this tool, it is excellent!

Only thing missing is the lack of temperature date from the RM Pro+, is this in the pipeline?

Cheers!

**Comment by eschava** [comment]
Have you tried config parameter broadlink_rm_temperature_interval ?
Instructions are here https://github.com/eschava/broadlink-mqtt#subscription-to-current-temperature-rm2-device

**Comment by Sc0th** [comment]
Hi, thanks for getting back to me, I have 5 devices in total, the 3 'RM Pro' devices are publishing the temperature perfectly, the two 'RM Pro+' devices report 0.0 - so it does appear to be a specific issue with the + models.

**Comment by eschava** [comment]
Issue https://github.com/mjg59/python-broadlink/issues/133 says that RM Pro+ has no temperature sensor

**Comment by Sc0th** [comment]
Hehe, yes that is indeed correct, I will get back under my rock, thank you for humouring me :)
