### ISSUE TITLE
RM Pro Enhancement Request: act as RF receiver

### ISSUE THREAD

**Issue by tlc76** [eschava/broadlink-mqtt#41]
Hi,

I have a RM Pro device and I need to use it as a RF receiver.
I have lots of RF devices (e.g. light switches, door sensors, fire detectors) that can only emit a **fixed** 433 MHz RF code but I do not have any device capable of receiving those codes. The RM Pro device however would do a very good job, as it could capture the codes and allow further processing via MQTT.
RM Pro has the "learning mode" function, so it is physically capable to receive RF codes.

Please consider adding this functionality as an option to the default "learning mode".

Thanks a lot!

**Comment by eschava** [comment]
Could you please check the latest version? Unfortunately, I have no RF compatible device and cannot test this functionality
You should use `recordrf`/`autorf` messages instead of `record`/`auto` for RF recording/smart replay
