### ISSUE TITLE
In which format are the codes stored?

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [eschava/broadlink-mqtt#42]
Maybe a stupid question to ask, but is there any documentation about the format used to store the IR codes (Pronto Hex? LIRC?) ? Also, are there any tools around to convert popular formats into the format `broadlink-mqtt` understands?

Cheers, and thanks for the great work!

**Comment by eschava** [comment]
It's a raw Hex format for data received from python-broadlink library
Btw, broadlink_cli utility uses the same format

**Comment by FabrizioRomanoGenovese** [comment]
This is very helpful, thanks. I've found this script to convert codes to `broadlink` and `broadlink_base_64` formats from raw: https://github.com/elupus/irgen I still have to test it but I am leaving this information here in case someone finds it useful!
