### ISSUE TITLE
BG1 Devices

### ISSUE THREAD

**Issue by cgorms** [eschava/broadlink-mqtt#46]
I have 2  BG1 devices, mqtt.py discovers multiple devices but identifies them as unknown... how do I configure these.

They are https://www.bgelectrical.uk/wiring-devices/moulded/smart-sockets#822/HC-01

**Comment by eschava** [comment]
I've already added support for BG1 device but parent https://github.com/mjg59/python-broadlink library still misses it.
There already is a pull request (https://github.com/mjg59/python-broadlink/pull/290) and you either need to wait until it will be merged to the main project tree or install python-broadlink from https://github.com/barnybug/python-broadlink/tree/add_bgelectrical_sockets branch using next command (not tested by me though)

pip install git+https://github.com/barnybug/python-broadlink@add_bgelectrical_sockets

**Comment by cgorms** [comment]
Thank you that works 🙂

**Comment by cgorms** [comment]
Thank you that works 🙂
