### ISSUE TITLE
Panasonic air conditioner record but replay not working

### ISSUE THREAD

**Issue by thachphongphong** [eschava/broadlink-mqtt#52]
I try to record panasonic air conditioner but not working:
1. record -> broadlink/aircon/bedroom/power
2. replay -> broadlink/aircon/bedroom/power
no thing happended.

**Comment by eschava** [comment]
Could you please show logs of the app when record and replay commands were received?

**Comment by thachphongphong** [comment]
When i record i pointed remote to device not point to broadlink. I think you should update readme :)
It's working now. Thanks for your reply.
