### ISSUE TITLE
Support For the new Broadlink RM4C

### ISSUE THREAD

**Issue by soloam** [eschava/broadlink-mqtt#54]
Hello, will this work on the new Broadlink RM4C? 

Any one tried it? 

Thank you

**Comment by eschava** [comment]
Looks like your device is not fully supported according to the issue tracker of the parent library
https://github.com/mjg59/python-broadlink/issues/301

**Comment by VincentSC** [comment]
Support was merged on 16 March

**Comment by eschava** [comment]
Committed support for it

**Comment by soloam** [comment]
Thank you

Best regards

**Comment by soloam** [comment]
There are 2 versions of the RM4, the RM4C and the RM4, the difference is that the RM4 can control the temperature and humidity (needs a different usb cable with the sensor, sold separately). Do you know if both are supprted?

Thank you

**Comment by eschava** [comment]
It seems so
