### ISSUE TITLE
I can't replay or learn new IR codes

### ISSUE THREAD

**Issue by joanisc** [eschava/broadlink-mqtt#56]
![image](https://user-images.githubusercontent.com/5494786/72758022-e25a6500-3bd1-11ea-99fb-554fc49d48ee.png)
What am I losing? Any help?

**Comment by eschava** [comment]
You should send commands through MQTT broker, not enter them in console
How are you going to use this tool?

**Comment by joanisc** [comment]
Thank you! I would like to control my broadlink RM mini 3 to control the AC and integrate it in openhab. I tried to send the message using mosquitto_ pub. I'm doing it right?

**Comment by eschava** [comment]
You're doing everything right, but your Broadlink device was not recognized for some reason
You can see that "Connected to **'Unknown'** Broadlink device" message
Looks like you are affected by the issue filed at https://github.com/mjg59/python-broadlink/issues/307

**Comment by joanisc** [comment]
Thank you!
