### ISSUE TITLE
Which Pi?

### ISSUE THREAD

**Issue by Diez66** [eschava/broadlink-mqtt#57]
This is a "Happy Feedback".
What model Pi can you use. My experiance.

Never fed back before but, if it helps others?, I had a few problems but got it working on Pi V1 but not reliably, it would very occasionally record an RF remote but it was no real use. Two Days Playing!!
I had tried on an old Pi2 that was doing DHCP and more, this had real issues with python 3, my bad, also struggled with leaning new stuff, again me!.

What I wanted to feedback>>>>>
Starting with a (new) Pi3 and the latest "raspbian-buster" image, it worked within 5 minutes of starting off. THANKS!

So is there a minimum Pi it should work on?
Wanted to put it on a Pi Zero W, should it be OK?
Maybe put the minimum in the requirements?

As an asside, I am also finding that when i set up a RFrecord it normally works, if I try a second record, I just get lots of zeros(s). If I stop the script and re run, all good for one more record.
For me this is not to big as I have only a few devices but if I can feedback to help, ask.

Thanks

**Comment by imeuro** [comment]
hi currently trying on a Pi2, running Buster and python3. no issues here!
