### ISSUE TITLE
RM MINI 3 D

### ISSUE THREAD

**Issue by marcol79** [eschava/broadlink-mqtt#59]
Do not work with rm mini 3 d

**Comment by eschava** [comment]
Please update python-broadlink library and recheck

**Comment by marcol79** [comment]
where i download it?

**Comment by eschava** [comment]
It was installed automatically when you did "pip install -r requirements.txt"
You can execute "pip install --upgrade -r requirements.txt" to upgrade all dependencies

**Comment by marcol79** [comment]
hi I have reinstalled everything now. I have two broadlinks but when I run "python mqtt.py record -> commands / cond / power" it gives me an error "Traceback (most recent call last):
  File "mqtt.py", line 4, in <module>
    import broadlink # pip install broadlink
ImportError: No module named broadlink
"

**Comment by eschava** [comment]
Looks same as https://github.com/mjg59/python-broadlink/issues/330
You can track it

**Comment by ArtjeB** [comment]
I have got the RM4 (redbean) running, so below mentioned devices are now supported:
>       rm4: 0x51da,  # RM4b
>               0x5f36,  # RM Mini 3
>               0x610f,  # RM4c
>               0x610e,  # RM4 mini
>               0x62be  # RM4c

This by updating the broadlink python library and changing the code below in _mqtt.py_. Furtermore, you need to run the scripts using python**3**

```
         # RM2 record/replay control
             if device.type == 'RM2':
             file = dirname + "commands/" + command
             handy_file = file + '/' + action
```

into
```
         # RM2 record/replay control
             if device.type == 'RM4' or 'RM2':
             file = dirname + "commands/" + command
             handy_file = file + '/' + action
```


I propose to change the master code. I tried to commit the code change, but I am not used to work with Github.

**Comment by eschava** [comment]
I've committed support for RM4, please update
