### ISSUE TITLE
How to install the integration

### ISSUE THREAD

**Issue by Edu-ST** [eschava/broadlink-mqtt#63]
Hi,

Sorry for basic question but to use this integration (RM4 Mini), it doesn't running Update directly from your repository?
If it is different method, do you have some description how to?

Thank you!!

**Comment by eschava** [comment]
sorry, your question is not clear
do you already have the previous version installed?

**Comment by Edu-ST** [comment]
Sorry, I will ask by another way...   

How to install your integration?   Updating from Repository or Copy/Paste your code?

I have anything previous version installed.

**Comment by eschava** [comment]
updating from repository
git pull should work in almost 100%
