### ISSUE TITLE
Request: Unify  MQTT action and status states

### ISSUE THREAD

**Issue by ElectricImpossible** [eschava/broadlink-mqtt#67]
Could I request an option to enable a post of power on/off to the broadlink/power/1 topics to utilise 1 or 0 to match the values output by the status topic?

My control UI (Pimatic) doesnt seem to allow a different on message type for control and status values and I cant figure out how to parse the status in JSON.

I'm utilising a bg1

Thanks

**Comment by eschava** [comment]
Absolutely agree! Should be fixed now

**Comment by ElectricImpossible** [comment]
Great work, thanks!

For completeness I can use 1 and 0 to control the power topic!

👍
