### ISSUE TITLE
Only works with Python 3

### ISSUE THREAD

**Issue by VincentSC** [eschava/broadlink-mqtt#72]
Python 2 gives problems. Therefore first line in `mqtt.py` needs to be:
> #!/usr/bin/env python3

See also last comment in #64

**Comment by VincentSC** [comment]
Also added some info to #29

**Comment by eschava** [comment]
Python 2 gives problems for some devices only, most of them work normally

**Comment by eschava** [comment]
Also, there is a pull request to fix compatibility with Python 2
https://github.com/mjg59/python-broadlink/pull/368
