### ISSUE TITLE
"Authentication failed" when connecting to wifi with Broadlink app (works on IHC)

### ISSUE THREAD

**Issue by BrunoZumba** [eschava/broadlink-mqtt#77]
Hello,

I'm having trouble using broadlink-mqtt when I connect my broadlink to wifi via the "new" Broadlink App (https://play.google.com/store/apps/details?id=cn.com.broadlink.econtrol.international).
After connecting to wifi with the app, when I start broadlink-mqtt i get the following error:
(I masked the IP and MAC)
```
$ ./broadlink-mqtt/mqtt.py
[2020-06-30 10:19:29,407] DEBUG Connected to 'RM2' Broadlink device at '192.168.XXX.YYY' (MAC AA:BB:CC:DD:EE:FF) and started listening for commands at MQTT topic having prefix 'broadlink/RM2_DD_EE_FF/'
Traceback (most recent call last):
  File "/home/pi/broadlink-mqtt/mqtt.py", line 580, in <module>
    devices = get_device(cf)
  File "/home/pi/broadlink-mqtt/mqtt.py", line 363, in get_device
    device = configure_device(device, topic_prefix + mqtt_subprefix)
  File "/home/pi/broadlink-mqtt/mqtt.py", line 394, in configure_device
    device.auth()
  File "/home/pi/.local/lib/python3.7/site-packages/broadlink/__init__.py", line 225, in auth
    check_error(response[0x22:0x24])
  File "/home/pi/.local/lib/python3.7/site-packages/broadlink/exceptions.py", line 97, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: Authentication failed

```
(The error happens both on lookup or when I set the device_type, address and MAC on custom.conf).

But the weird thing is that when I connect the broadlink on wifi with the IHC App (https://play.google.com/store/apps/details?id=cn.com.broadlink.econtrol.plus) It works fine.

I made the test twice (connecting via broadlink app, getting the error, then resetting broadlink, connecting with IHC and working) and with 2 different broadlinks.

Right now it is working fine for me, so it's ok if you guys close the issue.
I don't know if you are aware of this (or maybe it's something wrong with my configurations). But i think it would help some people if this was stated on the README page until it gets fixed.

Thanks for your work on this project!

**Comment by eschava** [comment]
Yes, it's a known issue and it definitely needs mentioning in the README
I'll try to adjust it
Thanks for your investigation!

**Comment by PAJ320** [comment]
I am unable to connect my BG sockets via the IHC app, only the new BG app works. Consequently I am getting the Authentication error mentioned above.
Do you have any suggestions for a workaround?

**Comment by eschava** [comment]
I've added a "known issues" section in the docs with this item only. Unfortunately, I'm not good at writing docs but I hope it will help somebody

**Comment by VincentSC** [comment]
@eschava Here's some text you can use

# Connect Broadlink device to wifi
You need to use the [Broadlink e-control app](https://play.google.com/store/apps/details?id=com.broadlink.rmt) or [Broadlink Intelligent Home Center](https://play.google.com/store/apps/details?id=cn.com.broadlink.econtrol.plus) to get the device connected to wifi. **Don't use** [BroadLink -Universal TV Remote](https://play.google.com/store/apps/details?id=cn.com.broadlink.econtrol.international), as it is known to lock devices. Other apps have not been tested.

Press the reset-button for 5+ seconds till the led starts flashing continuously. Now it is in "smart mode". Go to the `e-control` or `Intelligent home Center` app and add a new device. Fill in the wifi-credentials and start scanning while staying close to the device. When the led starts flashing slower, it is discovered. When the led turns off, it is configured.

You (theoretically) can configure multiple devices at one.

# Error messages
- **ERROR No Broadlink devices found**: No wifi-device on the network is a Broadlink device recognized by the library. If you see a device connected to your wifi that starts with the device type, like "RM4-44-b6-a2" for a RM4, then it could be that the device is not supported yet. If you see no device connected (which is in most cases), make sure it is connected to your wifi network.
- **broadlink.exceptions.AuthenticationError: Authentication failed**: The device is locked by an app. Use the instructions above to reset the device and connect it to wifi without lock.
- **with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s: AttributeError: __exit__**: this library requires Python3, and you used Python2. Start the library with `python3 ./mqtt.py`.

**Comment by eschava** [comment]
> @eschava Here's some text you can use
> 
> # Connect Broadlink device to wifi

Thanks a lot! Added these texts to the information page

**Comment by VincentSC** [comment]
Just ping me here, if you want me to write texts or to reformulate some texts
