### ISSUE TITLE
Add retain flag option to last will and birth messages

### ISSUE THREAD

**Issue by soloam** [eschava/broadlink-mqtt#78]
Referring to https://github.com/eschava/broadlink-mqtt/issues/71

Hello @eschava thank you for your work on this, very simple to use but so useful! Is it possible to make the birth and will message retained? (or make it optional in the config), only this message! This is useful to know the status of the client on the controller (for example home assistant) start. If The controller starts after the broadlink client, it will not receive the bridge status if this is not retained.

Thank you

**Comment by eschava** [comment]
Good idea! Thank you
Changed the code to always sent last will and birth messages as retained

**Comment by soloam** [comment]
That was fast! Thank you @eschava
