### ISSUE TITLE
button sequence/combo? 

### ISSUE THREAD

**Issue by farhanito** [eschava/broadlink-mqtt#8]
any idea how to effectively send series of button press in one go? 
for example, to activate channel 123 on my tv, i have to send button 1, button 2, and button 3 in quick succession 

thanks

**Comment by eschava** [comment]
My first idea is to have plain text files in folder macro/ with text like

file: **macro/samsung_on**
content:
**tv/samsung/on
pause 250
tv/samsung/mute**

and to activate this macro have to send MQTT message like
TOPIC: **macro/samsung_on**
PAYLOAD: **macro**

Do you like it?

**Comment by farhanito** [comment]
seems easy enough. yes please, thank you

**Comment by eschava** [comment]
should be fixed, please check
