### ISSUE TITLE
Alternative TOPIC structure for macros

### ISSUE THREAD

**Issue by digitlength** [eschava/broadlink-mqtt#88]
Is it possible, as with the commands, to have an alternative method of activating macros?

For example, it would be super useful (for me, of course!), if we could send the message "my_macro_name" to topic `broadlink/<device-id>/macros`

This means only a single topic needs to be configured to activate macros, and the message contains the name of the macro.

**Comment by eschava** [comment]
Done, please check
I used `broadlink/<device-id>/macro` topic for this

**Comment by digitlength** [comment]
Perfect! Works like a charm!
