### ISSUE TITLE
RM4C mini Bestcon Unknown

### ISSUE THREAD

**Issue by mike01483** [eschava/broadlink-mqtt#91]
Used Broadlink app to connect Bestcon RM4C mini to wifi.
Already use multiple devices so have set 
**device_type = 'multiple_lookup'**  in custom.conf
Running **python3 ./mqtt.py** in terminal I see

`[2021-01-24 16:53:45,752] DEBUG Connected to 'Unknown' Broadlink device at '192.168.3.132' (MAC a0:43:b0:31:d3:63) and started listening to MQTT commands at 'broadlink/Unknown_31_d3_63/#'
`
As well as other broadlink devices.

Sending commands via mosquitto_pub
replay -> broadlink/Unknown_31_d3_63/soundbar/power
in terminal I get

`[2021-01-24 16:55:46,276] DEBUG Received MQTT message broadlink/Unknown_31_d3_63/soundbar/power replay
[2021-01-24 16:55:46,277] WARNING Unrecognized MQTT message replay
`
The above command works fine if sent to other broadlink devices.

Have deleted RM4C from broadlink app and re-added wifi again without continuing full configuration.
Have installed the latest broadlink-mqtt revision.
But can't get this device working.

**Comment by thiagogsr** [comment]
This issue is related to the https://github.com/mjg59/python-broadlink library. I'm also using a RM4C device, I'm able to debug it:

```python
import broadlink

devices = broadlink.discover(timeout=5)

>>> for device in devices:
...   print(device.type)
...
RM2
Unknown
```

**Comment by thiagogsr** [comment]
It has been added to [python-broadlink](https://github.com/mjg59/python-broadlink), but it hasn't been released: https://github.com/mjg59/python-broadlink/commit/bc6719dc2a125ef6979d017f98fe640a9d959b72. I've fixed it installing the package from Github with the command:
```
pip3 install --upgrade git+https://github.com/mjg59/python-broadlink.git@master#egg=broadlink
```

**Comment by mike01483** [comment]
Thanks -  added
0x6539: (rm4, "RM4C mini", "Broadlink"),
to
/usr/local/lib/python3.7/dist-packages/broadlink/__init__.py
and RM4C mini is working great.
