### ISSUE TITLE
Docker Container and Multiple BG1

### ISSUE THREAD

**Issue by cgorms** [eschava/broadlink-mqtt#92]
Hi @eschava

I've used your dockerfile and created a working container. I'm running another container for eclipse-mosquito, when I perform a direct connection to a device it works. However, when I set the mqtt.conf file to multiple_lookup it doesn't discover any devices on my network and I receive the following error 'ERROR No Broadlink devices found'.

Do I need to do something to my docker container?

**Comment by eschava** [comment]
Sorry, I've never used Docker container, this configuration has been created by one of the users
@psyciknz maybe you could help?

**Comment by cgorms** [comment]
No worries @eschava fingers crossed @psyciknz can help 👍

**Comment by cgorms** [comment]
I'm found a solution. The docker container running Broadlink-mqtt needs to use the host network not bridge network.

**Comment by psyciknz** [comment]
Glad you solved it.  Another option if needed is the docker container can use macvlan....which means that container gets a new IP address of its own (or in my case, I put it in my iot network where my broad link devices exist)
