### ISSUE TITLE
RMMIN type_device nslookup

### ISSUE THREAD

**Issue by wakan** [eschava/broadlink-mqtt#93]
DEBUG Connected to 'RMMINI' Broadlink device at

WARNING Unrecognized MQTT message record

Thx for project

**Comment by wakan** [comment]
If you want, it's cool.
Possible solve :
`
diff --git a/mqtt.py b/mqtt.py
index b9b281e..b11420d 100755
--- a/mqtt.py
+++ b/mqtt.py
@@ -182,7 +182,7 @@ def on_message(client, device, msg):
             return
 
         # RM2/RM4 record/replay control
-        if device.type == 'RM2' or device.type == 'RM4':
+        if device.type == 'RM2' or device.type == 'RM4' or device.type == 'RMMINI':
             file = dirname + "commands/" + command
             handy_file = file + '/' + action
` 
Thanks a lot.

**Comment by eschava** [comment]
Done

**Comment by wakan** [comment]
Thanks a lot
